language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn clean
  - yarn build
  - yarn test
